#!/usr/bin/python3.12

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

import struct

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train / 255.0
x_test = x_test / 255.0

#y_train = to_categorical(y_train, 10)
#y_test = to_categorical(y_test, 10)

with open("mnist_train.bin", "wb") as file:
	count, row, col = x_train.shape
	file.write(struct.pack('>i', count))
	for mat in x_train:
		for row in mat:
			for val in row:
				file.write(struct.pack('>d', val))
	for val in y_train:
		file.write(struct.pack('>i', val))

with open("mnist_test.bin", "wb") as file:
	count, row, col = x_test.shape
	file.write(struct.pack('>i', count))
	for mat in x_test:
		for row in mat:
			for val in row:
				file.write(struct.pack('>d', val))
	for val in y_test:
		file.write(struct.pack('>i', val))					