#!/usr/bin/python3

from http.server import BaseHTTPRequestHandler, HTTPServer

class Server(BaseHTTPRequestHandler):
	def do_GET(self):
		self.send_response(200)
		self.send_header("Context-type", "text/html")
		self.end_headers()
		self.wfile.write(bytes("Hello.world\n", "utf-8"))

PORT = 8080
server_address = ("", PORT)

# Create and run server
server = HTTPServer(server_address, Server)
try:
	server.serve_forever()
except KeyboardInterrupt:
	pass
server.server_close()
