# Project: c-smile-vm
# Makefile created by Dev-C++ 4.9.3.0

CC   = g++.exe
WINDRES = windres.exe
RES  = 
OBJ  = vm_interpret.o archive.o compiler.o cs_ext.o cs_main.o debug.o mm.o rtl.o rtl_array.o rtl_blob.o rtl_date.o rtl_file.o rtl_map.o rtl_regexp.o rtl_socket.o rtl_stream.o rtl_string.o scanner.o streams.o sym_table.o things.o threads.o VM.o $(RES)
LIBS =  -L"D:\Dev-C++\lib"
INCS =  -I"D:\Dev-C++\include"  -I"D:\Dev-C++\include\g++-3"  -I"D:\Dev-C++\include" 
BIN  = c-smile-vm.a
CFLAGS = $(INCS) -DCOMPILER -fexceptions -g3

.PHONY: clean

all: c-smile-vm.a

clean:
	rm -f $(OBJ) $(BIN)

$(BIN): $(OBJ)
	ar r $(BIN) $(OBJ)
	ranlib $(BIN)

vm_interpret.o: vm_interpret.cpp 
	$(CC) -c vm_interpret.cpp -o vm_interpret.o $(CFLAGS)

archive.o: archive.cpp 
	$(CC) -c archive.cpp -o archive.o $(CFLAGS)

compiler.o: compiler.cpp 
	$(CC) -c compiler.cpp -o compiler.o $(CFLAGS)

cs_ext.o: cs_ext.cpp 
	$(CC) -c cs_ext.cpp -o cs_ext.o $(CFLAGS)

cs_main.o: cs_main.cpp 
	$(CC) -c cs_main.cpp -o cs_main.o $(CFLAGS)

debug.o: debug.cpp 
	$(CC) -c debug.cpp -o debug.o $(CFLAGS)

mm.o: mm.cpp 
	$(CC) -c mm.cpp -o mm.o $(CFLAGS)

rtl.o: rtl.cpp 
	$(CC) -c rtl.cpp -o rtl.o $(CFLAGS)

rtl_array.o: rtl_array.cpp 
	$(CC) -c rtl_array.cpp -o rtl_array.o $(CFLAGS)

rtl_blob.o: rtl_blob.cpp 
	$(CC) -c rtl_blob.cpp -o rtl_blob.o $(CFLAGS)

rtl_date.o: rtl_date.cpp 
	$(CC) -c rtl_date.cpp -o rtl_date.o $(CFLAGS)

rtl_file.o: rtl_file.cpp 
	$(CC) -c rtl_file.cpp -o rtl_file.o $(CFLAGS)

rtl_map.o: rtl_map.cpp 
	$(CC) -c rtl_map.cpp -o rtl_map.o $(CFLAGS)

rtl_regexp.o: rtl_regexp.cpp 
	$(CC) -c rtl_regexp.cpp -o rtl_regexp.o $(CFLAGS)

rtl_socket.o: rtl_socket.cpp 
	$(CC) -c rtl_socket.cpp -o rtl_socket.o $(CFLAGS)

rtl_stream.o: rtl_stream.cpp 
	$(CC) -c rtl_stream.cpp -o rtl_stream.o $(CFLAGS)

rtl_string.o: rtl_string.cpp 
	$(CC) -c rtl_string.cpp -o rtl_string.o $(CFLAGS)

scanner.o: scanner.cpp 
	$(CC) -c scanner.cpp -o scanner.o $(CFLAGS)

streams.o: streams.cpp 
	$(CC) -c streams.cpp -o streams.o $(CFLAGS)

sym_table.o: sym_table.cpp 
	$(CC) -c sym_table.cpp -o sym_table.o $(CFLAGS)

things.o: things.cpp 
	$(CC) -c things.cpp -o things.o $(CFLAGS)

threads.o: threads.cpp 
	$(CC) -c threads.cpp -o threads.o $(CFLAGS)

VM.o: VM.cpp 
	$(CC) -c VM.cpp -o VM.o $(CFLAGS)
